server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # 是否注册到eureka服务器中;
    fetch-registry: false   # 是否从注册中心拉取信息;
    service-url:
      defaultZone: http://localhost:7001/eureka # EurekaServer的地址
